=== gunagopi/wso2example/EIProjects/CountryServicesRegistry/Countries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://com.example.CountryServices/Countries"
xmlns:tns="http://com.example.CountryServices/Countries" elementFormDefault="qualified">

    <xs:element name="Countries" type="tns:CountriesType"></xs:element>
    
    <xs:complexType name="CountriesType">
    	<xs:sequence>
    		<xs:element name="Country" type="tns:CountryType" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="CountryType">
    	<xs:sequence>
    		<xs:element name="Name" type="xs:string"></xs:element>
    		<xs:element name="Capital" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== gunagopi/wso2example/Resources/Countries.xml
<Countries xmlns="http://com.example.CountryServices/Countries" xsi:schemaLocation="http://com.example.CountryServices/Countries Countries.xsd " xmlns:tns="http://com.example.CountryServices/Countries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Country>
      <Name>United Kingdom</Name>
      <Capital>London</Capital>
   </Country>
   <Country>
      <Name>India</Name>
      <Capital>New Delhi</Capital>
   </Country>
   <Country>
      <Name>Italy</Name>
      <Capital>Rome</Capital>
   </Country>
   <Country>
      <Name>Switzerland</Name>
      <Capital>Bern</Capital>
   </Country>
   <Country>
      <Name>France</Name>
      <Capital>Paris</Capital>
   </Country>
</Countries>
